---
title: "Ggplot"
author: "Jeremy"
date: "12/10/2018"
output: html_document
---

```{r}
library(magrittr)
library(tidyverse)
library(shiny)
library(data.table) # data mgmt
library(gtools) # combination
library(ggplot2) # graphics
library(plotly) # interactive graphics
library(e1071)
library(caret)
library(cowplot)
library(caTools)
library(pROC)
library(MASS)
library(car)
```

```{r}
# data preparation

# load the data
df <- read.csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")

# remove rows with NAN values
df <- df[complete.cases(df),]

# Trun SeniorCitizen column to categorical 
df$SeniorCitizen <- as.factor(ifelse(df$SeniorCitizen==1, 'YES', 'NO'))
```

```{r}
# Cleaning the Categorical features
df <- data.frame(lapply(df, function(x) {
                  gsub("No internet service", "No", x)}))

df <- data.frame(lapply(df, function(x) {
                  gsub("No phone service", "No", x)}))

# Standardising Continuous features
num_columns <- c("tenure", "MonthlyCharges", "TotalCharges")
df[num_columns] <- sapply(df[num_columns], as.numeric)

df_int <- df[,c("tenure", "MonthlyCharges", "TotalCharges")]
df_int <- data.frame(scale(df_int))

# Creating derived features for tenure
#max(df$tenure)
#min(df$tenure)
df <- mutate(df, tenure_bin = tenure)

df$tenure_bin[df$tenure_bin >= 0 & df$tenure_bin <= 12] <- '0-1 year'
df$tenure_bin[df$tenure_bin > 12 & df$tenure_bin <= 24] <- '1-2 years'
df$tenure_bin[df$tenure_bin > 24 & df$tenure_bin <= 36] <- '2-3 years'
df$tenure_bin[df$tenure_bin > 36 & df$tenure_bin <= 48] <- '3-4 years'
df$tenure_bin[df$tenure_bin > 48 & df$tenure_bin <= 60] <- '4-5 years'
df$tenure_bin[df$tenure_bin > 60 & df$tenure_bin <= 72] <- '5-6 years'

df$tenure_bin <- as.factor(df$tenure_bin)

# Creating Dummy Variables
df_categorical <- df[,-c(1,6,19,20)]

dummy<- data.frame(sapply(df_categorical,function(x) data.frame(model.matrix(~x-1,data =df_categorical))[,-1]))

# Combining the data
df_final <- cbind(df_int,dummy)

# Splitting the data
set.seed(666)
Churn_train = sample.split(df_final$Churn, SplitRatio = 0.7)
train = df_final[Churn_train,]
test = df_final[!(Churn_train),]
```

```{r}
library(scales)
df1 <- df %>%
group_by(InternetService, Churn) %>% 
summarise(Count = n())%>% 
mutate(percent = prop.table(Count)*100)

ggplot(data = df1, aes(reorder(Churn, -percent), percent))+
geom_bar(aes(fill = InternetService),stat = "identity", position = "dodge") + 
geom_text(aes(fill = InternetService, label = sprintf("%.2f%%", percent)),  
              position = position_dodge(width = .9), hjust = -0.1,
              size = 3) + 
geom_jitter(color="yellow",shape=2) +
xlab("Churn") + 
ylab("Churn Percent") +
ggtitle("Customer attrition rate with Internet Service type") + coord_flip()

ggsave('g1.png', width = 16, height = 9, dpi = 100)
```

```{r}
df2 <- df %>%
group_by(tenure_bin, Churn) %>% 
summarise(Count = n())%>% 
mutate(percent = prop.table(Count)*100)

ggplot(data = df2, aes(reorder(tenure_bin, -percent), percent))+
geom_bar(aes(fill = Churn),stat = "identity", position = "dodge")+
geom_text(aes(fill = Churn, label = sprintf("%.2f%%", percent)), 
          position = position_dodge(width = .9), vjust = -0.1, size =3)+
geom_path()+ 
xlab("Tenure group") + 
ylab("Churn Percent") +
ggtitle("Customer attrition in tenure groups")

ggsave('g2.png', width = 16, height = 9, dpi = 100)
```

```{r}
ggplot(data = df, aes(x = Churn, y = TotalCharges)) + 
geom_boxplot(aes(fill=Churn)) +
geom_dotplot() + 
facet_wrap(~ PaymentMethod, nrow=2) +
xlab("Churn") +
ggtitle("Total charges v.s. Payment Method with customer attrition") 

ggsave('g3.png', width = 16, height = 9, dpi = 100)
```

```{r}
ggplot(data = df, aes(x = Churn, y = MonthlyCharges)) + 
geom_boxplot(aes(fill=Churn)) +
facet_wrap(~ PaymentMethod, nrow=2) +
geom_dotplot() + 
xlab("Churn") +
ggtitle("Monthly charges v.s. Payment Method with customer attrition")

ggsave('g4.png', width = 16, height = 9, dpi = 100)
```