---
title: "Shinny app"
author: "Jeremy"
date: "12/9/2018"
output: html_document
runtime: shiny
---

```{r echo = FALSE, include = FALSE}
library(MASS)
library(dplyr)
library(pROC)
library(shiny)
library(ggplot2)
library(randomForest)
library(rsconnect)
library(caTools)
rsconnect::setAccountInfo(name='jeremylee',
			  token='6FAF9226E829A0436578D798DE497638',
			  secret='aUtriP5EwOioa9+ueb0UujuvVpaF9bUEibaidIAl')
```

```{r echo = FALSE, include = FALSE}
# data preparation

# load the data
df <- read.csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")

# remove rows with NAN values
df <- df[complete.cases(df),]

# Trun SeniorCitizen column to categorical 
df$SeniorCitizen <- as.factor(ifelse(df$SeniorCitizen==1, 'YES', 'NO'))
```

```{r include = FALSE}
# Cleaning the Categorical features
df <- data.frame(lapply(df, function(x) {
                  gsub("No internet service", "No", x)}))

df <- data.frame(lapply(df, function(x) {
                  gsub("No phone service", "No", x)}))

# Standardising Continuous features
num_columns <- c("tenure", "MonthlyCharges", "TotalCharges")
df[num_columns] <- sapply(df[num_columns], as.numeric)

df_int <- df[,c("tenure", "MonthlyCharges", "TotalCharges")]
df_int <- data.frame(scale(df_int))

# Creating derived features for tenure
#max(df$tenure)
#min(df$tenure)
df <- mutate(df, tenure_bin = tenure)

df$tenure_bin[df$tenure_bin >= 0 & df$tenure_bin <= 12] <- '0-1 year'
df$tenure_bin[df$tenure_bin > 12 & df$tenure_bin <= 24] <- '1-2 years'
df$tenure_bin[df$tenure_bin > 24 & df$tenure_bin <= 36] <- '2-3 years'
df$tenure_bin[df$tenure_bin > 36 & df$tenure_bin <= 48] <- '3-4 years'
df$tenure_bin[df$tenure_bin > 48 & df$tenure_bin <= 60] <- '4-5 years'
df$tenure_bin[df$tenure_bin > 60 & df$tenure_bin <= 72] <- '5-6 years'

df$tenure_bin <- as.factor(df$tenure_bin)

# Creating Dummy Variables
df_categorical <- df[,-c(1,6,19,20)]

dummy<- data.frame(sapply(df_categorical,function(x) data.frame(model.matrix(~x-1,data =df_categorical))[,-1]))

# Combining the data
df_final <- cbind(df_int,dummy)

# Splitting the data
set.seed(666)
Churn_train = sample.split(df_final$Churn, SplitRatio = 0.7)
train = df_final[Churn_train,]
test = df_final[!(Churn_train),]
```

```{r echo = FALSE}
# Define UI for application that plots features of movies
ui <- fluidPage(
  titlePanel("Model Prediction Accuracy"),
  br(),
  # Sidebar layout with a input and output definitions
  sidebarLayout(

    # Inputs
    sidebarPanel(

      # Select variable for y-axis
      selectInput(inputId = "model",
                  label = "Model:",
                  choices = c("Logistic model" , 
                              "Random forest model"  
                               ),
                  selected = "Logistic model"),

      # Select variable for x-axis
      sliderInput(inputId = "feature_num",
                  label = "Number of features used for Logistic model:",
                  min = 1, max = length(train)-1,
                  value = 1)
    ),

    # Outputs
    mainPanel(
      plotOutput(outputId = "roc_curve")
    )
  )
)

# Define server function required to create prediction models
server <- function(input, output) {
  get_formu <- reactive({
    vars <- colnames(train)[1:input$feature_num]
      formu <- paste('Churn ~', paste(vars, collapse = '+'))
      formu <- as.formula(formu)
      formu
  })
  get_data <- reactive({
    if(input$model == 'Logistic model'){
      
      model_3 <-glm(formula = get_formu(), family = "binomial", data = train)
      
      pred <- predict(model_3, type = "response", newdata = test[,-24])
      
      
      glm.roc <- roc(response = test$Churn, predictor = as.numeric(pred))
      glm.roc
    }else if(input$model == 'Random forest model'){
      model.rf <- randomForest(Churn~., data=train, proximity=FALSE,importance = FALSE,ntree=500,mtry=floor(sqrt(length(colnames(train)))), do.trace=FALSE)
      testPred <- predict(model.rf, newdata=test[,-24])
      rf.roc <- roc(response = test$Churn, predictor = as.numeric(testPred))
      rf.roc
    }
  })
  # Create roccurve
  output$roc_curve <- renderPlot({
    roc <- get_data()
    ggroc(data = roc ) + ggtitle(paste("Roc curve for", input$model, sep = ' ')) + 
      annotate("text", x = .80, y = .20, 
           label = paste("AUC =", round(roc$auc, 2)))
  })
}
# Create the Shiny app object
shinyApp(ui = ui, server = server)
```
